version: "3.8"
services:
  fastapi-nano:
    container_name: "fastapi-nano"
    image: "fastapi-nano:latest"
    env_file:
      - .env
    build:
      context: ./
      args:
        script: /start-reload.sh
      dockerfile: Dockerfile
      labels:
        - fastapi-nano
    command: ["/start-reload.sh"]
    volumes:
        - .:/code
    ports:
      - 5000:5000
